#!/usr/bin/with-contenv bash

echo $(id)

iptables-restore < /etc/iptables/rules.v4

iptables -I OUTPUT -o eth0 -p tcp --dport 53 -j ACCEPT
iptables -I OUTPUT -o eth0 -p udp --dport 53 -j ACCEPT

PROTO=$(sed -n '/proto /p' /openvpn.conf | awk '{print $2}')

sed -n '/remote /p' /openvpn.conf | while IFS= read -r remote ; do
  EXCLUSION_HOST=$(echo $remote | awk '{print $2}')
  EXCLUSION_PORT=$(echo $remote | awk '{print $3}')
  EXCLUSION_PROT=$(echo $remote | awk '{print $4}')
  if [[ -z $EXCLUSION_PROT ]]; then
    EXCLUSION_PROT=$PROTO
  fi
  if expr "$ip" : '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' >/dev/null; then
    true
  else
    EXCLUSION_HOST=$(getent hosts $EXCLUSION_HOST | awk '{print $1}')
  fi
  #iptables -I OUTPUT 3 -o eth0 -p $EXCLUSION_PROT -d $EXCLUSION_HOST --dport $EXCLUSION_PORT -j ACCEPT
  iptables -I OUTPUT 3 -o eth0 -p tcp -d $EXCLUSION_HOST --dport $EXCLUSION_PORT -j ACCEPT
  iptables -I OUTPUT 3 -o eth0 -p udp -d $EXCLUSION_HOST --dport $EXCLUSION_PORT -j ACCEPT
done

#iptables -D OUTPUT -o eth0 -p tcp --dport 53 -j ACCEPT
#iptables -D OUTPUT -o eth0 -p udp --dport 53 -j ACCEPT

iptables -L
exit 
