#!/usr/bin/with-contenv bash

# Determine if setup is needed
if [ ! -f /usr/sbin/openvpn ] && \
[ -f /usr/bin/apt ]; then
  ## Ubuntu
  apt-get update
  apt-get install --no-install-recommends -y \
    iptables \
    openvpn
fi
if [ ! -f /usr/sbin/openvpn ] && \
[ -f /sbin/apk ]; then
  # Alpine
  apk add --no-cache \
    iptables \
    openvpn \
fi

cp /etc/iptables/rules.v4 /etc/iptables/rules.sed.v4
sed -i "s/SPECIFIC_ALLOWED_OUTBOUND/$IPTABLES_EXCEPTION/g" /etc/iptables/rules.sed.v4
iptables-restore < /etc/iptables/rules.sed.v4

